language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: willsheffler
  password:
    secure: XGj0e9pHKS1tCvHYHkD2LmoiKInJ0nqPfkRY/PLk0AtX+QC6fPXjC7raZBJ3DnJKs/zLelEAmUYp3fXrD5LxDNPdRuRxxLNQfK+CkPHfKPjd5uS98mapGlVHkSxv+Z6ievQn4RYGjCgXpW3OIUsi5gltPun1NrJIskW7MB4QWLxMMY/Oeikn2IKxF4QYynaqh5PLYLxVmsaWg45nNtWMTDhwKKTtEnXz+oiK5mpZ8LdeUot78Fi53kPvZmHYEl4xefypQa8o1FzzRyaSA5PNvSab/884eh+4RIeNrkojk/pKLMKVRYFYmqQVPBQRVw5kzcrNYjwqG/F0IO1rrl5HxOC3jnxPAZM0cxAi6Pn7IPi0ytKAHzcp3cBN1kuK02z4foFjPIaUabaG2VwKxq0fx6QNN4LjQ4SxV77tK83ob/i5CNK8aQ7UGo86SvYsvDmim2XXHQBzbwIluyTviBEmMV4wLkDCxNvH2z5GR925n610DZncAw1/su5SAiDnpw8YTHzz6G1T/TrUSa5pqcJVsGBoYo2WqtChkIcYmFxGvGa4yzLY+pmAojBzhqwtGvbdUysmKHotO3GIm4FOsWX0YRVaCxqcJAQ4gHGrz9nF1lIC3FPe9oIPpra9eYKrAQHcUPBTCi+Y43Zrrc+/Vr9Kd1E0vJIe0R1acehces5V324=
  on:
    tags: true
    repo: willsheffler/bcc
    python: 3.6
