language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: willsheffler
  password:
    secure: PvpBkAaxFEceT4kchQ8R+2BPh1641vMjLWdxl2KB+AmUW4d2b2FQcHfKDWIsYkwms42Apu3B9VoSkttt1ToFrsvJvVKOX3DiV2yWVceuIZlXfHakT2xCzPYlX7INt9iCkxrAdmrkAIlgyTfKkgxK3/smwJ9GLDg/iril4dhX+SNROALA7345i3ZouUcM8t44yvMcQgQK5ne9GPuXj8lFALlC+7bn67Svre/HsdHhdOvcuIYjevGNofxXpeUzU2wV+GbVXwCE5Dcu68ObRXUM3k0lf5edAjDnoTbLPompHqX6pENRWggRI6oET3B0JishV7ccYNE6X58QpoWP1Y0+W/HPX2Yz9N3sCbDqhQG46yRHxc+5vXPBDygqdXxfEAzuNSCehCF/IHx199FAjCOM9xDE9cidePv3AoMAsXIOVbQ0fwhPjvLSRbEMHNZfttRwRhFAMnc2ENfXaSso6pfu8H6GJR8QfKZlQFSAlSeSR0wmf9Y59jYQZeHDak05OUuMnXomhoGmWt5/GgwngeWRfreivf4oDHvJOdDQSxFB0n7VHzyOLKzZ5KtR6/HGSy7ce5zpmBNBwDk8rirxabnbw5bhAQub6zBPRZ+aF7f/lQHmkmgRMGOFON827DKoRbQGrbDZR019/U5MxoBG9Zi7MRIRHdm9gAaGxEFOHhlK8Gw=
  on:
    tags: true
    repo: willsheffler/bcc
    python: 3.6
