language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: willsheffler
  password:
    secure: nuuG/khRCFaJQga91H4TWqkquf4V5YdI/A8Bq/AnygzoF9w+5Kt4/VQIb78P4mWxhUcnAVKhHbt6YaKQ6142yezG7VwSdOnuxc+9bOmITj9STaBFewYLQqsM3+N5l0T1+26nY95qU5btH0SjCLklb9H7GxqeU1zrdAC0AipMW/tHgpCjKuH0hr4IG8ziNeLXDySlsWaDXUfLd47fb7iXb2zt3bRC8oIBqDL9noUV1jt8dpvmYF9ry0USbVZ64rYZ77LxAbvBxvoFuUELZ0L2x36pFI4Cxaz6Ep2kWbWY56SZGuY9CEwGoZeKRi6ADWFm8BzB1Bq0nVagkWS8Kkmn+F299+urCqRHG3I76Finax4wUV+ugaRxtjwfCloy/ULK0iz+3yPOpwGznlzJIlpJPmrL5N6cAZzMZDmUevVdHTfHtU9PafSyryw/AZwUvzBSNQCJzp7DLeraPTtFA2qX/dG7L7ccvQXuM5xL9TBvuYoxvh8mpDOpXScX5AWsjhX8VmBaafAi4fFahZ4sZ7KkBDphpmWTIld7K5C8/sA0xQC83gA3+HEyIsqvmEqBSkw5FdWsJMKf3eq3iN5Skfr47un1sYULWvRhLNhuqqYZq8a767ztf+aw6X/Xk0Za5A3doXNYtY1Rjrss6vGgto8Z/V9sUNPEExOLHBM0klo04uw=
  on:
    tags: true
    repo: willsheffler/bcc
    python: 3.6
