language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: willsheffler
  password:
    secure: czknPCmglk5ZudfYNys6SdTDeUdYvfggdra+ABHRJaRwgfpgnjkYTwJ1vVlcdJW9PHEPI3XGVRAWoNQ1WWJOw8pveZzlYVcp86t8CZF0MraJjrWZ9RnNaOJJRY/FHmqgYHBJdrFi0TaJHOIvnibE9qRe1y2/jI7Z5LZHuk1+v9PsUUdqsiirJOupCEif8Ah5DWCVeI/vbDl3R1BvBmmp+dT1JydDfTzj/J07DZ9Nr5PRu9vap4K9VuXhU7iPv5cDqKDbmXYqjD7tgOFQTTPVwIomZhsmQmlSiEb8PlTqmNCWUZljvxZOcbh101Y4jo6L0E0dfEGpXmqB14xm3NgICZc56RQjjxVh9JKw5u9xSmQBXxqZW3+beyNrYSyzZ4Ta5hvhyLWsNJAzf+789DhH8AdSm5OAV/b52HSV3KzNEkz5tfAiaZc8iyfQIc6Fiuqv6XgLyWEEree6Abwcyr0W20xt6enhxGHXJcG6HYwgewBWjBXT6Qkc4R/xb6AUd3RF6BiEZIrt47m54hVl5xRwvTs/mJAu9GHK70rQjOQoKrX+oWH7veLD5KlVidcgvBPh8KHAVrH3Qlhj5/8No2m4BMqDMkz2y7RwW/BqU2+vj5WFWilTC+wq/LRpv9gxmd/ojNXMmafxaytfxn6VM+sxMB+sSFQ7Ub3NCo+LHFtquck=
  on:
    tags: true
    repo: willsheffler/bcc
    python: 3.6
